{
 "title": "pokeapi — Prometheus en 4 piezas",
 "tags": [
  "pokeapi",
  "charla"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Redis",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pokeapi_redis_disponible" }
   ]
  },
  {
   "title": "Sesiones activas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pokeapi_sesiones_activas" }
   ]
  },
  {
   "title": "Peticiones/s (total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pokeapi_http_peticiones_total[1m]))"
    }
   ]
  },
  {
   "title": "Latencia p95",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pokeapi_http_duracion_segundos_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Peticiones/s por rol",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pokeapi_http_peticiones_total[1m])) by (rol)",
     "legendFormat": "{{rol}}"
    }
   ]
  },
  {
   "title": "Consultas pokémon: caché (⚡) vs API (🌐)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pokeapi_pokemon_consultas_total[5m])) by (origen)",
     "legendFormat": "{{origen}}"
    }
   ]
  },
  {
   "title": "Latencia HTTP p95 (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pokeapi_http_duracion_segundos_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Usuarios por rol",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pokeapi_usuarios_por_rol", "legendFormat": "{{rol}}" }
   ]
  }
 ]
}